// AUTO-GENERATED by scripts/generate-changelog-data.ts from docs/CHANGELOG.md.
// Do not hand-edit — run `node scripts/generate-changelog-data.ts` instead.

import type { ChangelogEntry } from "@/lib/changelog-parse";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    "id": "908f14c611b1",
    "summary": "On the phone, tapping anywhere around the page in the chapter editor (the margins, the chapter title row, the pills) puts the keyboard away.",
    "text": "On the phone, tapping anywhere around the page in the chapter editor (the margins, the chapter title row, the pills) puts the keyboard away. The selected tab in the manuscript tab bar now fills its whole segment of the bar, rounder at the two ends and flatter in the middle. The Ciciro chat shows its quick-action chips on an empty chat only; once you are talking they sit behind a sparkle button. \"Previously on\" is now two or three sentences (web and phone), and the phone clamps it to five lines with Show more."
  },
  {
    "id": "49d59f11259e",
    "summary": "**Who knows what** is now chapter by chapter (web and phone).",
    "text": "**Who knows what** is now chapter by chapter (web and phone). A character can know, suspect, believe wrongly, or not know something, from a chapter until the chapter it changes in; facts saved as \"believes\" read as \"suspects\". The Knowledge screen opens at the chapter you have open, with a chapter scrubber, a timeline per character that shows what ended and what replaced it, and a grid by topic with an optional Reader column from canon.md. Ciciro's editing, the continuity check and What changed now see only what characters know by the chapter in question, never a later one."
  },
  {
    "id": "b6f350ee51c3",
    "summary": "Ask Ciciro in chat to record who knows what (\"note that Joe suspects Suzy has the pen\"): it records it against the chapter you have open, or the one you name,…",
    "text": "Ask Ciciro in chat to record who knows what (\"note that Joe suspects Suzy has the pen\"): it records it against the chapter you have open, or the one you name, says exactly what it recorded, and can change or remove it. \"What does Joe know at this point?\" answers from the ledger as of your chapter. This works in Chat only too."
  },
  {
    "id": "8e99383771c9",
    "summary": "Fixed: on the phone, typing in a chapter after switching from another one no longer fails to save with an \"Unexpected null or undefined value\" error.",
    "text": "Fixed: on the phone, typing in a chapter after switching from another one no longer fails to save with an \"Unexpected null or undefined value\" error."
  },
  {
    "id": "5e8eb03edf28",
    "summary": "The phone's Ciciro chat now has the website's quick-action chips above the message box (What needs work most?, Critique this chapter, Tighten dialogue, Find lo…",
    "text": "The phone's Ciciro chat now has the website's quick-action chips above the message box (What needs work most?, Critique this chapter, Tighten dialogue, Find loose ends, and the rest, different for a novel, screenplay, blog post or journal). A tap sends the brief; the ones that work on a passage need words highlighted in the manuscript first, and the ones that change the manuscript need Allow edits. This replaces the three starter prompts the empty chat used to offer. Rewrite from the writing tools now works on the words you have highlighted."
  },
  {
    "id": "e2b381867c13",
    "summary": "On the phone, a manuscript has a **Manuscript details** tool (in the Tools row on the chapters screen) to change its title, author and logline, move it between…",
    "text": "On the phone, a manuscript has a **Manuscript details** tool (in the Tools row on the chapters screen) to change its title, author and logline, move it between folders, or delete it. Chapters can be renamed from a title line above the page, which also says which chapter you are in. The chapters screen shows the manuscript's total word count."
  },
  {
    "id": "0d983283fa45",
    "summary": "Phone Settings is grouped under Appearance, Writing, Ciciro, Goals and reminders, and Privacy, and Writing history is listed there.",
    "text": "Phone Settings is grouped under Appearance, Writing, Ciciro, Goals and reminders, and Privacy, and Writing history is listed there. The + menu on the manuscripts list is only for creating (new manuscript, import, new folder), and the writing-tools grid no longer repeats Chapters and Typography. Sign-in and sign-up move from field to field with Return and submit from the password. The manuscript tab bar now labels its three tabs (Chapters, Manuscript, Ciciro), the empty chat's prompt is no longer drawn upside down, and deleting a manuscript returns to a library that shows its remaining manuscripts instead of a blank list."
  },
  {
    "id": "7d924e0b53e7",
    "summary": "The phone app has the website's Archive look as two new themes, **Ciciro** and **Ciciro Night**, now the default for anyone who has not picked a theme.",
    "text": "The phone app has the website's Archive look as two new themes, **Ciciro** and **Ciciro Night**, now the default for anyone who has not picked a theme. The chapters screen is restyled in it (new typefaces, folder-tab chapter cards, paper-stock stage chips) and the app's text uses Newsreader, Instrument Sans and JetBrains Mono. Four themes are renamed: Sage is **Marginalia**, Ember is **First Edition**, Walnut is **Bookshelf**, Candle is **Dog-Ear**; Parchment and Inkwell keep their names, and everyone keeps the theme they picked. This needs a new app build; an over-the-air update does not carry the fonts."
  },
  {
    "id": "4705d8722e5a",
    "summary": "New **Allow edits / Chat only** switch under Ciciro's chat (web and phone).",
    "text": "New **Allow edits / Chat only** switch under Ciciro's chat (web and phone). It belongs to the conversation: a new chat starts on Allow edits, and Chat only stays on for as long as that conversation continues. In Chat only, Ciciro answers and discusses but never changes your manuscript; the server withholds its writing tools, so it holds even when a page or app is out of date."
  },
  {
    "id": "4ca366f23f13",
    "summary": "**Stop** in Ciciro's chat (web and phone) now actually stops a request.",
    "text": "**Stop** in Ciciro's chat (web and phone) now actually stops a request. Ciciro finishes the step it is on, then stops before its next tool call; anything it already wrote stays and can be undone."
  },
  {
    "id": "f3ae4e2e3793",
    "summary": "Auto-draft and the chat's draft tool no longer put text that was cut off mid-sentence into your chapter.",
    "text": "Auto-draft and the chat's draft tool no longer put text that was cut off mid-sentence into your chapter. A beat that runs past its length limit now fails and can be retried, and Recap and chapter summaries keep their previous version instead of saving a cut-off one."
  },
  {
    "id": "45a8d2e04376",
    "summary": "The website has a new look, the Archive design language: paper texture, richer color, and a light/dark toggle on the public pages.",
    "text": "The website has a new look, the Archive design language: paper texture, richer color, and a light/dark toggle on the public pages. `/` is now the landing page for signed-out visitors (the library for signed-in ones), with app screenshots and short demos, and `/launch` redirects there. The pricing page shows an early-access discount when one is set up (see `docs/billing.md`)."
  },
  {
    "id": "8e0e1e55b2fd",
    "summary": "New opt-in setting, **Experimental writing prompt** (Settings, web and phone, off by default): Ciciro's drafts follow craft defaults that avoid habits common i…",
    "text": "New opt-in setting, **Experimental writing prompt** (Settings, web and phone, off by default): Ciciro's drafts follow craft defaults that avoid habits common in model-written prose (feelings mirrored by the weather, stated themes, \"not X but Y\" contrasts, tidy endings), and a check after each draft points the editor at any that slipped through. Your `style.md`, your voice notes, and anything a brief asks for still win. Off, drafting works exactly as before."
  },
  {
    "id": "85c87257d317",
    "summary": "Em dashes stay off by default; a `- Em dashes: allowed` line in `style.md` switches them on for drafts, with or without the experimental setting.",
    "text": "Em dashes stay off by default; a `- Em dashes: allowed` line in `style.md` switches them on for drafts, with or without the experimental setting."
  },
  {
    "id": "e3e7ea752d34",
    "summary": "Drafter default is now Claude Sonnet 5.5 (`claude-sonnet-5-5`), was Claude Sonnet 5 (`claude-sonnet-5`).",
    "text": "Drafter default is now Claude Sonnet 5.5 (`claude-sonnet-5-5`), was Claude Sonnet 5 (`claude-sonnet-5`). Same per-token price. No request-shape changes were needed. Anthropic's migration guidance for Sonnet 5.5 is: \"`thinking: {type: \"disabled\"}` returns a 400 - to turn thinking off, send `thinking: {type: \"between_tools\"}`\" (a breaking change from Sonnet 5, which accepted `{type: \"disabled\"}`). But that only affects callers that explicitly disabled thinking. Per Anthropic's own thinking/effort reference table, *omitting* `thinking` already ran adaptive (thinking on) on Sonnet 5 - \"Omitting `thinking`: Runs adaptive\" - and continues to run adaptive on Sonnet 5.5 - \"Omitting `thinking`: Runs **adaptive**\". Every Ciciro drafter call (`recap.ts`, `continuity.ts`, `weekly-review.ts`, `style-analysis.ts`, `tools.ts` dispatch_draft, `autowrite.ts` draftBeat) omits `thinking` rather than disabling it, so the `between_tools` note does not apply and behavior is unchanged."
  },
  {
    "id": "b62c11be8e4e",
    "summary": "Ciciro now sends email: a link to confirm your address after signing up, a welcome once it's confirmed, password reset links (\"Forgot password?\" on web and mob…",
    "text": "Ciciro now sends email: a link to confirm your address after signing up, a welcome once it's confirmed, password reset links (\"Forgot password?\" on web and mobile sign-in), and a note when an account is deleted. Settings shows when your email isn't confirmed yet and can resend the link."
  },
  {
    "id": "d71d36cdd001",
    "summary": "Settings (web and mobile) can now export all of your data as one zip and delete your account.",
    "text": "Settings (web and mobile) can now export all of your data as one zip and delete your account. `/account/delete` explains account deletion publicly, for the App Store and Google Play deletion requirements."
  },
  {
    "id": "8b53fd70bc02",
    "summary": "Sign in with Apple and Google on the web and in the app, next to email and password.",
    "text": "Sign in with Apple and Google on the web and in the app, next to email and password. A verified email that matches an existing account signs into it. An account without a password confirms deletion by typing DELETE, and deleting it revokes Ciciro's Sign in with Apple access. See `docs/social-sign-in.md`."
  },
  {
    "id": "3f14e16d68eb",
    "summary": "Settings (web and mobile) now shows the models Ciciro is actually running: Editor, Drafter, Quick drafts, and the Groq router when configured.",
    "text": "Settings (web and mobile) now shows the models Ciciro is actually running: Editor, Drafter, Quick drafts, and the Groq router when configured. Current defaults, set in `src/lib/anthropic.ts` and `src/lib/fast-lane.ts`: - Editor: Claude Opus 5 (`claude-opus-5`) - Drafter: Claude Sonnet 5 (`claude-sonnet-5`) - Quick drafts: Claude Haiku 4.5 (`claude-haiku-4-5`) - Router (when `GROQ_API_KEY` is set): Llama 3.1 8B (`llama-3.1-8b-instant`)"
  },
  {
    "id": "eaaf5c42b96b",
    "summary": "Editor default is now Claude Opus 5.5 (`claude-opus-5-5`), was Claude Opus 5 (`claude-opus-5`).",
    "text": "Editor default is now Claude Opus 5.5 (`claude-opus-5-5`), was Claude Opus 5 (`claude-opus-5`). The drafter stays on Claude Sonnet 5."
  }
];
