// AUTO-GENERATED by scripts/generate-changelog-data.ts from docs/CHANGELOG.md.
// Do not hand-edit — run `node scripts/generate-changelog-data.ts` instead.

import type { ChangelogEntry } from "@/lib/changelog-parse";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
  {
    "id": "f3ae4e2e3793",
    "summary": "Auto-draft and the chat's draft tool no longer put text that was cut off mid-sentence into your chapter.",
    "text": "Auto-draft and the chat's draft tool no longer put text that was cut off mid-sentence into your chapter. A beat that runs past its length limit now fails and can be retried, and Recap and chapter summaries keep their previous version instead of saving a cut-off one."
  },
  {
    "id": "45a8d2e04376",
    "summary": "The website has a new look, the Archive design language: paper texture, richer color, and a light/dark toggle on the public pages.",
    "text": "The website has a new look, the Archive design language: paper texture, richer color, and a light/dark toggle on the public pages. `/` is now the landing page for signed-out visitors (the library for signed-in ones), with app screenshots and short demos, and `/launch` redirects there. The pricing page shows an early-access discount when one is set up (see `docs/billing.md`)."
  },
  {
    "id": "8e0e1e55b2fd",
    "summary": "New opt-in setting, **Experimental writing prompt** (Settings, web and phone, off by default): Ciciro's drafts follow craft defaults that avoid habits common i…",
    "text": "New opt-in setting, **Experimental writing prompt** (Settings, web and phone, off by default): Ciciro's drafts follow craft defaults that avoid habits common in model-written prose (feelings mirrored by the weather, stated themes, \"not X but Y\" contrasts, tidy endings), and a check after each draft points the editor at any that slipped through. Your `style.md`, your voice notes, and anything a brief asks for still win. Off, drafting works exactly as before."
  },
  {
    "id": "85c87257d317",
    "summary": "Em dashes stay off by default; a `- Em dashes: allowed` line in `style.md` switches them on for drafts, with or without the experimental setting.",
    "text": "Em dashes stay off by default; a `- Em dashes: allowed` line in `style.md` switches them on for drafts, with or without the experimental setting."
  },
  {
    "id": "e3e7ea752d34",
    "summary": "Drafter default is now Claude Sonnet 5.5 (`claude-sonnet-5-5`), was Claude Sonnet 5 (`claude-sonnet-5`).",
    "text": "Drafter default is now Claude Sonnet 5.5 (`claude-sonnet-5-5`), was Claude Sonnet 5 (`claude-sonnet-5`). Same per-token price. No request-shape changes were needed. Anthropic's migration guidance for Sonnet 5.5 is: \"`thinking: {type: \"disabled\"}` returns a 400 - to turn thinking off, send `thinking: {type: \"between_tools\"}`\" (a breaking change from Sonnet 5, which accepted `{type: \"disabled\"}`). But that only affects callers that explicitly disabled thinking. Per Anthropic's own thinking/effort reference table, *omitting* `thinking` already ran adaptive (thinking on) on Sonnet 5 - \"Omitting `thinking`: Runs adaptive\" - and continues to run adaptive on Sonnet 5.5 - \"Omitting `thinking`: Runs **adaptive**\". Every Ciciro drafter call (`recap.ts`, `continuity.ts`, `weekly-review.ts`, `style-analysis.ts`, `tools.ts` dispatch_draft, `autowrite.ts` draftBeat) omits `thinking` rather than disabling it, so the `between_tools` note does not apply and behavior is unchanged."
  },
  {
    "id": "b62c11be8e4e",
    "summary": "Ciciro now sends email: a link to confirm your address after signing up, a welcome once it's confirmed, password reset links (\"Forgot password?\" on web and mob…",
    "text": "Ciciro now sends email: a link to confirm your address after signing up, a welcome once it's confirmed, password reset links (\"Forgot password?\" on web and mobile sign-in), and a note when an account is deleted. Settings shows when your email isn't confirmed yet and can resend the link."
  },
  {
    "id": "d71d36cdd001",
    "summary": "Settings (web and mobile) can now export all of your data as one zip and delete your account.",
    "text": "Settings (web and mobile) can now export all of your data as one zip and delete your account. `/account/delete` explains account deletion publicly, for the App Store and Google Play deletion requirements."
  },
  {
    "id": "8b53fd70bc02",
    "summary": "Sign in with Apple and Google on the web and in the app, next to email and password.",
    "text": "Sign in with Apple and Google on the web and in the app, next to email and password. A verified email that matches an existing account signs into it. An account without a password confirms deletion by typing DELETE, and deleting it revokes Ciciro's Sign in with Apple access. See `docs/social-sign-in.md`."
  },
  {
    "id": "3f14e16d68eb",
    "summary": "Settings (web and mobile) now shows the models Ciciro is actually running: Editor, Drafter, Quick drafts, and the Groq router when configured.",
    "text": "Settings (web and mobile) now shows the models Ciciro is actually running: Editor, Drafter, Quick drafts, and the Groq router when configured. Current defaults, set in `src/lib/anthropic.ts` and `src/lib/fast-lane.ts`: - Editor: Claude Opus 5 (`claude-opus-5`) - Drafter: Claude Sonnet 5 (`claude-sonnet-5`) - Quick drafts: Claude Haiku 4.5 (`claude-haiku-4-5`) - Router (when `GROQ_API_KEY` is set): Llama 3.1 8B (`llama-3.1-8b-instant`)"
  },
  {
    "id": "eaaf5c42b96b",
    "summary": "Editor default is now Claude Opus 5.5 (`claude-opus-5-5`), was Claude Opus 5 (`claude-opus-5`).",
    "text": "Editor default is now Claude Opus 5.5 (`claude-opus-5-5`), was Claude Opus 5 (`claude-opus-5`). The drafter stays on Claude Sonnet 5."
  }
];
