import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseChangelogEntries } from "@/lib/changelog-parse";
import { CHANGELOG_ENTRIES } from "@/lib/changelog-data.generated";

const root = join(import.meta.dirname, "..");

describe("changelog parsing", () => {
  it("splits Unreleased into top-level bullets, dropping other sections", () => {
    const md = `# Changelog

## Unreleased

- First entry, one line.

- Second entry, spread across
  two lines that should join
  into one.

## 1.0.0

- Not unreleased, so this is left out.
`;
    const entries = parseChangelogEntries(md);
    expect(entries.map((e) => e.text)).toEqual([
      "First entry, one line.",
      "Second entry, spread across two lines that should join into one.",
    ]);
  });

  it("summarizes to the first sentence, and caps a long one with an ellipsis", () => {
    const md = `## Unreleased

- Short one. Second sentence is dropped from the summary.

- ${"x".repeat(200)}. Still one sentence but far too long for an email line.
`;
    const [short, long] = parseChangelogEntries(md);
    expect(short.summary).toBe("Short one.");
    expect(long.summary.length).toBeLessThanOrEqual(160);
    expect(long.summary.endsWith("…")).toBe(true);
  });

  it("gives every entry a stable, distinct id", () => {
    const entries = parseChangelogEntries(`## Unreleased\n\n- One.\n\n- Two.\n`);
    expect(new Set(entries.map((e) => e.id)).size).toBe(entries.length);
    expect(parseChangelogEntries(`## Unreleased\n\n- One.\n`)[0].id).toBe(entries[0].id);
  });

  it("returns nothing for a changelog with no Unreleased section", () => {
    expect(parseChangelogEntries("# Changelog\n\n## 1.0.0\n\n- Shipped.\n")).toEqual([]);
  });

  // src/lib/changelog-data.generated.ts is committed (see
  // scripts/generate-changelog-data.ts), not regenerated by `npm test`. This
  // fails when someone edits docs/CHANGELOG.md's Unreleased section without
  // re-running the generator, which every build does automatically
  // (scripts/build.mjs), but a local edit can still forget to.
  it("matches docs/CHANGELOG.md — run `npm run changelog:generate` if this fails", () => {
    const current = parseChangelogEntries(readFileSync(join(root, "docs/CHANGELOG.md"), "utf8"));
    expect(CHANGELOG_ENTRIES).toEqual(current);
  });
});
