import {
  deletePendingBible,
  deletePendingOps,
  deletePendingPosition,
  enqueuePendingOp,
  getBibleFile,
  getChapterSnapshot,
  getPendingPosition,
  getReadingPosition,
  insertChapterOp,
  listBibleFiles,
  listChapterSnapshots,
  listPendingBible,
  listPendingOps,
  upsertBibleFile,
  upsertChapterSnapshot,
  upsertPendingBible,
  upsertPendingPosition,
  upsertReadingPosition,
} from "./db";
import type { ReplicaStore } from "./replica-store";

export const sqliteReplica: ReplicaStore = {
  getChapter: getChapterSnapshot,
  listChapters: listChapterSnapshots,
  upsertChapter: upsertChapterSnapshot,
  insertOp: insertChapterOp,
  getBible: getBibleFile,
  listBible: listBibleFiles,
  upsertBible: upsertBibleFile,
  getPosition: getReadingPosition,
  upsertPosition: upsertReadingPosition,
  enqueueOp: enqueuePendingOp,
  listPendingOps,
  deletePendingOps,
  upsertPendingBible,
  listPendingBible,
  deletePendingBible,
  getPendingPosition,
  upsertPendingPosition,
  deletePendingPosition,
};
