// Regenerates src/lib/changelog-data.generated.ts from docs/CHANGELOG.md.
//
// Ciciro deploys to a Cloudflare Worker with no filesystem at request time,
// so the cron job that sends the product-update email (src/lib/email/cron.ts)
// and the /changelog page cannot fs.readFileSync the changelog themselves —
// this script does that once, at build time, and bakes the result into a
// plain, bundlable TS module both of them import as ordinary data.
//
// Run with: node scripts/generate-changelog-data.ts
// Wired into `npm run dev` and scripts/build.mjs, so it stays fresh; also
// committed, so `npm test` and `npm run typecheck` (which do not run either)
// see current data. test/changelog.test.ts fails if it drifts from
// docs/CHANGELOG.md, so CI catches a forgotten regeneration.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseChangelogEntries } from "../src/lib/changelog-parse.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const changelog = readFileSync(join(root, "docs/CHANGELOG.md"), "utf8");
const entries = parseChangelogEntries(changelog);

const out = `// AUTO-GENERATED by scripts/generate-changelog-data.ts from docs/CHANGELOG.md.
// Do not hand-edit — run \`node scripts/generate-changelog-data.ts\` instead.

import type { ChangelogEntry } from "@/lib/changelog-parse";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(join(root, "src/lib/changelog-data.generated.ts"), out);
console.log(`Wrote ${entries.length} changelog entries to src/lib/changelog-data.generated.ts`);
